openai:
  api_key: "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"
# todo merge api_keys
pinecone:
  api_key: "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"
  environment: "us-west1-gcp"
  index_name: "repository-analyzer"

repository:
  clone_path: "./cloned_repos"
